language: php

notifications:
  email:
    on_success: never

jobs:
  include:
    - stage: "PHP"
      name: "PHPStan on PS nightly and unit tests"
      language: php
      php: 7.2
      script:
        - composer install
        # PHP syntax check
        - bash -c '! (find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l | grep "Parse error")'
        # PHP cs fixer
        - composer run lint
        # PHP Unit
        - composer run unit-tests
        # PHP Stan
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:nightly
        - docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/web/module/tests/php/phpstan/phpstan.neon
